spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
  messages:
    basename: static/message/message
  mail:
    host: smtp.163.com
    username: leilvlong@163.com
    password: ITTMJXQIFGXXBWQN
  mvc:
    static-path-pattern: /static/**

  datasource:
    username: root
    password: Lei749581
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pingyougou?characterEncoding=utf-8
  redis:
    port: 6379
    password: Lei749581
    host: 127.0.0.1
    max-active: 10
    max-wait: 6000
    max-idle: 8
    min-idle: 5

mybatis:
  configuration:
    map-underscore-to-camel-case: true


redis:
  lock:
    config:
      redis-lock-prefix: LOCK