spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
  messages:
    basename: static/message/message
  mail:
    host: smtp.163.com
    username: leilvlong@163.com
    password: ITTMJXQIFGXXBWQN




