server:
  port: 8888
spring:
  application:
    name: config
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leilvlong/cloudconfig #配置git仓库地址
          searchPaths: cloud/config #配置仓库路径
#          username: leilvlong #访问git仓库的用户名
#          password: ENC(x8+lLvWdSBZnD35dP3uY1oyxr9Rp8NU/) #访问git仓库的用户密码
      label: master #配置仓库的分支
eureka:
  instance:
    hostname: 127.0.0.1
    instanceId: 127.0.0.1:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

pass: '{cipher}AQCztIfLC5jeJ3KLQwU2OHd4eGneh0r9bFe2mq+trLsIXAwHJAa0JST+H75E+2PjIVmyKuSVkj1Rl2/leDrPfbDt+Wwhkz+Q51KOOuVRdV5d8eALySbn1CRnxJvoaHi7zoTzplcnDfQtXZhkKxS/q912MnxIPTlOw70qTVHDDxkcqjHr5Ny6ahSuwWJaU79gpiUb/pxXZ/jZP5tfPFmi6QoWUOpGQ21ShOxjW16G1wAeDmWmfZBWZj/0fdRjpBUrjCZW667isdDDCgV0q5V3nWTySHx2ZkRG+vFRgYEYEhO2fMMEL7w7q/LZSNvBL7wBI/OJPha9s+4b6WYUxLNtUnfw2Xchxn3O6nMjxaGiTefalpb/OgDrouk4RUtUxRNi/is='